version: "3.9"

networks:
  my-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - mongo-rs-init
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo0:27017,mongo1:27017,mongo2:27017/?replicaSet=rs0
      - DB_NAME=robinhood
      - JWT_SECRET=secret
    ports:
      - ${PORT:-8080}:8080
    restart: unless-stopped
    command: ["cmd/main"]
    networks:
      - my-network
  mongo0:
    image: mongo:5
    container_name: mongo0
    command: >
      mongod
      --replSet rs0
      --bind_ip_all
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - ./data/db0:/data/db
    networks:
      - my-network

  mongo1:
    image: mongo:5
    container_name: mongo1
    command: >
      mongod
      --replSet rs0
      --bind_ip_all
    ports:
      - 27018:27017
    restart: unless-stopped
    volumes:
      - ./data/db1:/data/db
    networks:
      - my-network

  mongo2:
    image: mongo:5
    container_name: mongo2
    command: >
      mongod
      --replSet rs0
      --bind_ip_all
    ports:
      - 27019:27017
    restart: unless-stopped
    networks:
      - my-network

  mongo-rs-init:
    image: mongo:5
    container_name: mongo-rs-init
    depends_on:
      - mongo0
      - mongo1
      - mongo2
    entrypoint: ["replica_set_init.sh"]
    restart: on-failure
    volumes:
      - ./scripts/replica_set_init.sh:/usr/local/bin/replica_set_init.sh:ro
    networks:
      - my-network
